services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hh_test_app
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; make run'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=db
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8080:8080"
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: